#! /bin/sh

wmname LG3D &
picom --config ~/.config/picom/picom.conf &
picom &
${HOME}/.config/polybar/scripts/launch.sh &
xsetroot -cursor_name left_ptr &
feh --bg-scale /usr/share/backgrounds/Mountain.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
